require: rubocop-performance
inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false

LeadingCommentSpace:
  Enabled: false

LineLength:
  Enabled: false

SignalException:
  Enabled: false

# Don't care enough about this one
SpaceInsideHashLiteralBraces:
  Enabled: false

# Using $CHILD_STATUS instead of $?, etc
SpecialGlobalVars:
  Enabled: false

StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  Enabled: false
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes

# disabling a bunch of style linters
Layout/BlockAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Lint/Loop:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/packer/dataobject.rb'
    - 'lib/packer/envvar.rb'
    - 'lib/packer/macro.rb'
    - 'lib/packer/provisioners/powershell.rb'

Lint/Void:
  Exclude:
    - dashboard/spec/**/*

Naming/FileName:
  Exclude:
    - 'lib/packer-config.rb'

Layout/AccessModifierIndentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Layout/CaseIndentation:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NilComparison:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAfterNot:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

# As of rubocop 0.21, it thinks kwargs are useless assignments
UselessAssignment:
  Enabled: false

WordArray:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
