# Encoding: utf-8
require_relative 'file'
require_relative 'shell'
require_relative 'salt'
require_relative 'ansible'
require_relative 'chef/client'
require_relative 'chef/solo'
require_relative 'puppet/server'
require_relative 'puppet/masterless'
require_relative 'windows_restart'
